services:
  dev:
    image: node:lts-alpine
    container_name: vue_dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
      - "4173:4173"
    env_file:
      - .env
    tty: true
    command: sh -c "npm install && npm run dev"
